name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker Setup
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          export PATH=$PATH:/usr/local/bin
          docker-compose --version

      - name: Run Docker Compose
        run: docker-compose up -d
        env:
          POSTGRES_USER: discordbot-mdn
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: discordbot-mdn-db
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Check Container Status
        run: |
          docker ps --filter "status=exited" --filter "status=dead"
          if [ "$(docker ps -q --filter 'status=exited')" ]; then
            echo "Error: Some containers exited unexpectedly."
            exit 1
          fi

      - name: Stop Docker Compose
        run: docker-compose down
